### ISSUE TITLE
reasoning 

### ISSUE THREAD

**Issue by Yjing07** [joh-fischer/PlantLDM#46]
I don't know why the reasoning results are all noisy images.

**Comment by joh-schb** [comment]
What do you mean by reasoning results?

**Comment by Yjing07** [comment]
We found that training vqgan was successful, but the verification output after training ddpm was all noise.

**Comment by joh-schb** [comment]
How long did you train the ddpm?

**Comment by Yjing07** [comment]
We have trained 80,000 steps

**Comment by joh-schb** [comment]
I'm sorry, but with this few information I cannot help you properly, as there can be many reasons why it is not working. Did you train with the standard configuration and PlantNet dataset?
